name: Push to Azure DevOps

on:
  push:
    branches:
      - main # Replace with your branch name if needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Azure DevOps
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          # Clone the Azure DevOps repository
          git clone https://USERNAME:${AZURE_DEVOPS_PAT}@dev.azure.com/name: Push to Azure DevOps

on:
  push:
    branches:
      - main # Replace with your branch name if needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Azure DevOps
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          # Clone the Azure DevOps repository
          git clone https://USERNAME:${AZURE_DEVOPS_PAT}@dev.azure.com/name: Push to Azure DevOps

on:
  push:
    branches:
      - main # Replace with your branch name if needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Azure DevOps
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          # Clone the Azure DevOps repository
          git clone https://USERNAME:${AZURE_DEVOPS_PAT}@dev.azure.com/venubura123/project1

/_git/DEMOREPO1 azure-repo
          
          # Navigate to the cloned Azure DevOps repo
          cd azure-repo
          
          # Copy files from GitHub repo to Azure DevOps repo
          rsync -av --exclude='.git/' ../ .
          
          # Commit and push changes
          git add .
          git commit -m "Sync from GitHub Actions"
          git push origin main # Replace 'main' with your Azure DevOps repo branch name if different
/PROJECT_NAME/_git/REPO_NAME azure-repo
          
          # Navigate to the cloned Azure DevOps repo
          cd azure-repo
          
          # Copy files from GitHub repo to Azure DevOps repo
          rsync -av --exclude='.git/' ../ .
          
          # Commit and push changes
          git add .
          git commit -m "Sync from GitHub Actions"
          git push origin main # Replace 'main' with your Azure DevOps repo branch name if different
/PROJECT_NAME/_git/REPO_NAME azure-repo
          
          # Navigate to the cloned Azure DevOps repo
          cd azure-repo
          
          # Copy files from GitHub repo to Azure DevOps repo
          rsync -av --exclude='.git/' ../ .
          
          # Commit and push changes
          git add .
          git commit -m "Sync from GitHub Actions"
          git push origin main # Replace 'main' with your Azure DevOps repo branch name if different
